### ISSUE TITLE
[meta-issue] State of examples

### ISSUE THREAD

**Issue by randyzwitch** [shashi/Escher.jl#137]
Running on 0.4.6 on OSX, I found the following:

- [x] ~~boids.jl: Seems to work, WARNING: using Compose.px in module Main conflicts with an existing identifier.~~ #41 
- [x] ~~code-cell.jl: Seems to work~~
- [x] ~~form.jl: Seems to work~~
- [x] keypress.jl: Seems to work, example could be clearer around "focus" (focus on what?)
- [ ] latex.jl: Part of #136 (fixed pad, needs some clarification on purpose of example)
- [x] ~~layout2.jl: Seems to work~~
- [ ] mc.jl: Part of #136 (fixed pad, example still doesn't work) 
- [ ] minesweeper.jl: Broken, don't know how to fix
- [x] ~~plotting.jl: works, throws Gadfly.render warning~~ #41 
- [x] ~~recursive-layout.jl: works, throws Gadfly.render warning~~ #41
- [x] ~~vectorgraphics.jl: Seems to work~~

So not bad, can fix up `latex.jl` and `mc.jl` pretty quickly I'd think. Minesweeper doesn't lay out grid for me, it makes everything as rows (though the rows are interactive to spaces away from a mine)

**Comment by shashi** [comment]
Randy thanks for making this!

minesweeper.jl, is related to #122

**Comment by shashi** [comment]
I should add that I intended the current examples to be replaced by #67 . I haven't worked on it in a while

**Comment by randyzwitch** [comment]
Was going to hassle you about that, it's got merge conflicts ;)

**Comment by shashi** [comment]
There you go, I moved the non-doc commits which were causing the conflict to a new `drawer-panel` branch

**Comment by shashi** [comment]
(I'm merging master and fixing things up now)

**Comment by shashi** [comment]
Okay I have updated `content.jl` and `graphics.jl` which are the files that currently exist. You can hit ctrl+enter on any code cell to execute it.

**Comment by brandonkmiller** [comment]
@shashi @randyzwitch any idea what is causing mc.jl to not work correctly?  I have an app that uses a similar extraction that exhibits the same behaviour.  Sometimes the button fires and sometimes not.  I noticed that it started acting this way around the time Reactive.jl v0.3 was tagged which deprecated Input() and lift() - not sure if there's any relation.  I've tar'd up the last METADATA.jl that mc.jl worked with and it appears Reactive.jl was at version 0.2.4.

This issue seems hard to pin down because it appears the button fires, but it gets held up once it hits the Reactive function calls - and if you refresh - sometimes the simulation will execute.  Perhaps there was a breaking change from Reactive 0.2.4 to 0.3.0 (or maybe it's a Compose or Interact issue).  It's almost as if Julia is still compiling the app while the UI is already being rendered.  Sometimes if you wait after clicking the button for 30+ seconds I've seen it execute.

**Comment by brandonkmiller** [comment]
For what it's worth:
the issue seems to be around line 54:
```julia
result = map(sampleon(btn, N); typ=Any, init=nothing) do n
    run_simulate(n, running, current_approx)
end
```

Although again - it's a Heisenbug in that if you refresh repeatedly the simulation runs on occasion - which leads me to believe it's something with compilation

**Comment by shashi** [comment]
Reactive 0.3+ uses channels, so the updates are asynchronous - so if you do a `push!` and immediately start doing some computation, Reactive does not get any time to continue with its computation. I think we need to address this in Reactive somehow.
